#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: GPL-3.0-or-later

"""Convert Doxygen XML to Docusaurus Markdown files."""

import argparse
import logging
import pathlib
import sys

import doxmlparser

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logger = logging.getLogger(__name__)


def process_compound(dirName, baseName):
    """Process a Doxygen compound"""
    compoundPath = (dirName / baseName).with_suffix('.xml')
    compound = doxmlparser.compound.parse(compoundPath, silence=True)
    for compounddef in compound.get_compounddef():
        # kind = compounddef.get_kind()
        compounddef.get_kind()
        # if kind==DoxCompoundKind.CLASS:
        #     if is_documented(compounddef):
        # elif kind==DoxCompoundKind.STRUCT:
        # elif kind==DoxCompoundKind.UNION:
        # elif kind==DoxCompoundKind.INTERFACE:
        # elif kind==DoxCompoundKind.EXCEPTION:
        # elif kind==DoxCompoundKind.NAMESPACE:
        # elif kind==DoxCompoundKind.FILE:
        #     if is_documented(compounddef):
        # elif kind==DoxCompoundKind.GROUP:
        # elif kind==DoxCompoundKind.PAGE:
        # else:
        #     continue
        # parse_sections(compounddef,metrics)


def process_index(doxmlDir):
    """Process a Doxygen index"""
    indexPath = doxmlDir / 'index.xml'
    logger.debug('Parsing: %s', indexPath)
    index = doxmlparser.index.parse(indexPath, silence=True)
    logger.debug('Parsed v%s index', index.get_version())
    for compound in index.get_compound():
        logger.debug("%s %s", compound.get_kind(), compound.get_refid())
        process_compound(doxmlDir, compound.get_refid())


def main():
    """Main CLI entrypoint"""
    parser = argparse.ArgumentParser(
        description='Convert Doxygen XML to Docusaurus Markdown',
        epilog='foo')
    parser.add_argument('-d', '--debug', action='store_true', help="enable debugging")
    parser.add_argument(
        '-i', '--doxml', type=pathlib.Path, required=True,
        help='Doxygen XML directory', metavar='DIR')
    parser.add_argument(
        '-o', '--output', type=pathlib.Path, required=True,
        help='utput directory', metavar='DIR')
    args = parser.parse_args()
    if args.debug:
        logger.setLevel(logging.DEBUG)
    process_index(args.doxml)
    print("done")


if __name__ == '__main__':
    main()
