AbstractPokitServicePrivate
bool AbstractPokitServicePrivate::autoDiscover
Whether autodiscovery is enabled or not.
Referenced by connected, createServiceObject.
QLowEnergyController* AbstractPokitServicePrivate::controller
BLE controller to fetch the service from.
Referenced by AbstractPokitServicePrivate, connected, createServiceObject, discoveryFinished.
std::optional<PokitProduct> AbstractPokitServicePrivate::pokitProduct
The Pokit product controller is connected to.
Referenced by createServiceObject.
QLowEnergyService* AbstractPokitServicePrivate::service
BLE service to read/write characteristics.
Referenced by createServiceObject, disableCharacteristicNotificatons, enableCharacteristicNotificatons, getCharacteristic, readCharacteristic, serviceDiscovered, stateChanged.
QBluetoothUuid AbstractPokitServicePrivate::serviceUuid
UUIDs for service.
Referenced by DataLoggerServicePrivate::characteristicChanged, DsoServicePrivate::characteristicChanged, MultimeterServicePrivate::characteristicChanged, DataLoggerServicePrivate::characteristicRead, DeviceInfoServicePrivate::characteristicRead, DsoServicePrivate::characteristicRead, MultimeterServicePrivate::characteristicRead, StatusServicePrivate::characteristicRead, CalibrationServicePrivate::characteristicWritten, DataLoggerServicePrivate::characteristicWritten, DsoServicePrivate::characteristicWritten, MultimeterServicePrivate::characteristicWritten, StatusServicePrivate::characteristicWritten, createServiceObject, serviceDiscovered, StatusServicePrivate::serviceDiscovered.
AbstractPokitService* AbstractPokitServicePrivate::q_ptr
Internal q-pointer.
friend class TestAbstractPokitService
static AbstractPokitServicePrivate::Q_LOGGING_CATEGORY(lc, "pokit.ble.service", QtInfoMsg)
Logging category.
bool AbstractPokitServicePrivate::checkSize(const QString &label, const QByteArray &data, const int minSize, const int maxSize=-1, const bool failOnMax=false)
Returns false if data is smaller than minSize, otherwise returns failOnMax if data is bigger than maxSize, otherwise returns true.
A warning is logged if either minSize or maxSize is violated, regardless of the returned value; ie this funcion can be used to simply warn if data is too big, or it can be used to failed (return false) in that case.
References QString::arg, QByteArray::mid, QByteArray::size, toHexString, QObject::tr.
Referenced by StatusServicePrivate::characteristicRead, StatusServicePrivate::parseButtonPress, StatusServicePrivate::parseDeviceCharacteristics, DataLoggerServicePrivate::parseMetadata, DsoServicePrivate::parseMetadata, MultimeterServicePrivate::parseReading, StatusServicePrivate::parseStatus, StatusServicePrivate::parseTorchStatus.
QString AbstractPokitServicePrivate::toHexString(const QByteArray &data, const int maxSize=20)
Returns up to maxSize bytes of data as a human readable hexadecimal string.
If data exceeds maxSize, then data is elided in the middle. For example: toHex(QBytArray("\x1\x2\x3\x4\x5\x6",4);//"0x01,02,...,05,06"
References QString::arg, QString::fromLatin1, QByteArray::left, QByteArray::right, QByteArray::size, QByteArray::toHex.
Referenced by characteristicChanged, characteristicRead, characteristicWritten, checkSize, DataLoggerServicePrivate::parseMetadata, DataLoggerServicePrivate::parseSamples, DsoServicePrivate::parseSamples.
AbstractPokitServicePrivate::AbstractPokitServicePrivate(const QBluetoothUuid &serviceUuid, QLowEnergyController *controller, AbstractPokitService *const q)
Constructs a new AbstractPokitServicePrivate object with public implementation q. Note, typically the serviceUuid should be set validly, however, in the rare case that a service's UUID can vary (ie the Status Service), serviceUuid may be set to a null QBluetoothUuid here, and updated when the correct service UUID is known. StatusService::ServiceUuids StatusServicePrivate::serviceDiscovered
References QObject::connect, connected, QLowEnergyController::connected, controller, createServiceObject, discoveryFinished, QLowEnergyController::discoveryFinished, serviceDiscovered, QLowEnergyController::serviceDiscovered.
bool AbstractPokitServicePrivate::createServiceObject()
Creates an internal service object from the internal controller.
Any existing service object will not be replaced. Returns true if a service was created successfully, either now, or sometime previously.
References QString::arg, autoDiscover, characteristicChanged, QLowEnergyService::characteristicChanged, characteristicRead, QLowEnergyService::characteristicRead, characteristicWritten, QLowEnergyService::characteristicWritten, QObject::connect, controller, QLowEnergyController::createServiceObject, QLowEnergyService::descriptorRead, QLowEnergyService::descriptorWritten, QLowEnergyService::discoverDetails, QLowEnergyService::error, errorOccurred, QLowEnergyService::errorOccurred, QUuid::isNull, QLowEnergyDescriptor::name, pokitProduct, service, serviceUuid, stateChanged, QLowEnergyService::stateChanged, QUuid::toString, toString, QObject::tr, QLowEnergyDescriptor::uuid.
Referenced by AbstractPokitServicePrivate, discoveryFinished, serviceDiscovered.
QLowEnergyCharacteristic AbstractPokitServicePrivate::getCharacteristic(const QBluetoothUuid &uuid) const
Get uuid characteristc from the underlying service.
This helper function is equivalent to returnservice->characteristic(uuid); except that it performs some sanity checks, such as checking the service object pointer has been assigned first, and also logs failures in a consistent manner. uuid
References QString::arg, QLowEnergyService::characteristic, PokitDevice::charcteristicToString, QLowEnergyCharacteristic::isValid, service, PokitDevice::serviceToString, QLowEnergyService::serviceUuid, QLowEnergyService::state, QUuid::toString, QObject::tr.
Referenced by disableCharacteristicNotificatons, enableCharacteristicNotificatons, readCharacteristic.
bool AbstractPokitServicePrivate::readCharacteristic(const QBluetoothUuid &uuid)
Read the uuid characteristic.
If succesful, the QLowEnergyService::characteristicRead signal will be emitted by the internal service object. For convenience, derived classes should implement the characteristicRead() virtual function to handle the read value. Returns true if the characteristic read request was successfully queued, false otherwise. AbstractPokitService::readCharacteristics() AbstractPokitServicePrivate::characteristicRead()
References QString::arg, PokitDevice::charcteristicToString, getCharacteristic, QLowEnergyCharacteristic::isValid, QLowEnergyService::readCharacteristic, service, QUuid::toString, QObject::tr.
bool AbstractPokitServicePrivate::enableCharacteristicNotificatons(const QBluetoothUuid &uuid)
Enables client (Pokit device) side notification for characteristic uuid.
Returns true if the notication enable request was successfully queued, false otherwise. AbstractPokitServicePrivate::characteristicChanged AbstractPokitServicePrivate::disableCharacteristicNotificatons
References QString::arg, PokitDevice::charcteristicToString, QLowEnergyCharacteristic::descriptor, QByteArray::fromHex, getCharacteristic, QLowEnergyCharacteristic::isValid, QLowEnergyDescriptor::isValid, service, QUuid::toString, QObject::tr, QLowEnergyService::writeDescriptor.
bool AbstractPokitServicePrivate::disableCharacteristicNotificatons(const QBluetoothUuid &uuid)
Disables client (Pokit device) side notification for characteristic uuid.
Returns true if the notication disable request was successfully queued, false otherwise. AbstractPokitServicePrivate::characteristicChanged AbstractPokitServicePrivate::enableCharacteristicNotificatons
References QString::arg, PokitDevice::charcteristicToString, QLowEnergyCharacteristic::descriptor, QByteArray::fromHex, getCharacteristic, QLowEnergyCharacteristic::isValid, QLowEnergyDescriptor::isValid, service, QUuid::toString, QObject::tr, QLowEnergyService::writeDescriptor.
void AbstractPokitServicePrivate::connected()
Handles QLowEnergyController::connected events.
If autoDiscover is enabled, this will begin service discovery on the newly connected contoller. AbstractPokitService::autoDiscover()
References QString::arg, autoDiscover, controller, QLowEnergyController::discoverServices, QLowEnergyController::remoteAddress, QLowEnergyController::remoteDeviceUuid, QLowEnergyController::remoteName, QObject::sender, QBluetoothAddress::toString, QUuid::toString, QObject::tr.
Referenced by AbstractPokitServicePrivate.
void AbstractPokitServicePrivate::discoveryFinished()
Handles QLowEnergyController::discoveryFinished events.
As this event indicates that the conroller has finished discovering services, this function will invoke createServiceObject() to create the internal service object (if not already created).
References QString::arg, controller, createServiceObject, QObject::Q_EMIT, QLowEnergyController::remoteAddress, QLowEnergyController::remoteDeviceUuid, QLowEnergyController::remoteName, QObject::sender, QBluetoothAddress::toString, QUuid::toString, QObject::tr.
Referenced by AbstractPokitServicePrivate.
void AbstractPokitServicePrivate::errorOccurred(const QLowEnergyService::ServiceError newError)
Handles QLowEnergyController::errorOccurred events.
This function simply re-emits newError as AbstractPokitService::serviceErrorOccurred.
References QObject::Q_EMIT, QObject::tr.
Referenced by createServiceObject.
void AbstractPokitServicePrivate::serviceDiscovered(const QBluetoothUuid &newService)
Handles QLowEnergyController::serviceDiscovered events.
If the discovered service is the one this (or rather the derived) class wraps, then createServiceObject() will be invoked immediately (otherwise it will be invoked after full service discovery has completed, ie in discoveryFinished()).
References createServiceObject, service, serviceUuid, QObject::tr.
Referenced by AbstractPokitServicePrivate, StatusServicePrivate::serviceDiscovered.
void AbstractPokitServicePrivate::stateChanged(QLowEnergyService::ServiceState newState)
Handles QLowEnergyController::stateChanged events.
If newState indicates that service details have now been discovered, then AbstractPokitService::serviceDetailsDiscovered will be emitted. AbstractPokitService::autoDiscover()
References QString::arg, QLowEnergyService::characteristics, PokitDevice::charcteristicToString, QStringList::join, QObject::Q_EMIT, service, QObject::tr.
Referenced by createServiceObject.
void AbstractPokitServicePrivate::characteristicRead(const QLowEnergyCharacteristic &characteristic, const QByteArray &value)
Handles QLowEnergyService::characteristicRead events.
This base implementation simply debug logs the event. Derived classes should implement this function to handle the successful reads of characteristic, typically by parsing value, then emitting a speciailised signal.
References QString::arg, PokitDevice::charcteristicToString, QByteArray::size, toHexString, QUuid::toString, QObject::tr, QLowEnergyCharacteristic::uuid.
Referenced by DataLoggerServicePrivate::characteristicRead, DeviceInfoServicePrivate::characteristicRead, DsoServicePrivate::characteristicRead, MultimeterServicePrivate::characteristicRead, StatusServicePrivate::characteristicRead, createServiceObject.
void AbstractPokitServicePrivate::characteristicWritten(const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicWritten events.
This base implementation simply debug logs the event. Derived classes should implement this function to handle the successful writes of characteristic, typically by parsing newValue, then emitting a speciailised signal.
References QString::arg, PokitDevice::charcteristicToString, QByteArray::size, toHexString, QUuid::toString, QObject::tr, QLowEnergyCharacteristic::uuid.
Referenced by CalibrationServicePrivate::characteristicWritten, DataLoggerServicePrivate::characteristicWritten, DsoServicePrivate::characteristicWritten, MultimeterServicePrivate::characteristicWritten, StatusServicePrivate::characteristicWritten, createServiceObject.
void AbstractPokitServicePrivate::characteristicChanged(const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue)
Handles QLowEnergyService::characteristicChanged events.
This base implementation simply debug logs the event. If derived classes support characteristics with client-side notification (ie Notify, as opposed to Read or Write operations), they should implement this function to handle the successful reads of characteristic, typically by parsing value, then emitting a speciailised signal.
References QString::arg, PokitDevice::charcteristicToString, QByteArray::size, toHexString, QUuid::toString, QObject::tr, QLowEnergyCharacteristic::uuid.
Referenced by DataLoggerServicePrivate::characteristicChanged, DsoServicePrivate::characteristicChanged, MultimeterServicePrivate::characteristicChanged, createServiceObject.