StatusServicePrivate
friend class TestStatusService
StatusServicePrivate::StatusServicePrivate(QLowEnergyController *controller, StatusService *const q)
Constructs a new StatusServicePrivate object with public implementation q.
StatusService::DeviceCharacteristics StatusServicePrivate::parseDeviceCharacteristics(const QByteArray &value)
Parses the Device Characteristics value into a DeviceCharacteristics struct.
References AbstractPokitServicePrivate::checkSize, QByteArray::constData, QByteArray::mid, QObject::tr.
Referenced by characteristicRead, StatusService::deviceCharacteristics.
StatusService::Status StatusServicePrivate::parseStatus(const QByteArray &value)
Parses the Status value into a Status struct.
Note, not all Pokit devices support all members in Status. Specifically, the batteryStatus member is not usually set by Pokit Meter devices, so will be an invlalid BatteryStatus enum value (255) in that case.
References QString::arg, QByteArray::at, AbstractPokitServicePrivate::checkSize, QByteArray::constData, StatusService::Status::deviceStatus, QByteArray::mid, QByteArray::size, StatusService::toString, QObject::tr.
Referenced by characteristicRead, StatusService::status.
std::optional< StatusService::TorchStatus > StatusServicePrivate::parseTorchStatus(const QByteArray &value)
Parses the torch status value, and returns the corresponding TorchStatus.
References QString::arg, QByteArray::at, AbstractPokitServicePrivate::checkSize, StatusService::toString, QObject::tr.
Referenced by StatusService::torchStatus.
std::optional< StatusService::ButtonStatus > StatusServicePrivate::parseButtonPress(const QByteArray &value)
Parses the button press value, and returns the corresponding ButtonStatus.
References QString::arg, QByteArray::at, AbstractPokitServicePrivate::checkSize, StatusService::toString, QObject::tr.
Referenced by StatusService::buttonPress.
void StatusServicePrivate::serviceDiscovered(const QBluetoothUuid &newService) override
Handles QLowEnergyController::serviceDiscovered events.
Here we override the base implementation to detect if we're looking at a Pokit Meter, or Pokit Pro device, as the two devices have very slightly different Status Service UUIDs.
References StatusService::ServiceUuids::pokitMeter, StatusService::ServiceUuids::pokitPro, AbstractPokitServicePrivate::serviceDiscovered, AbstractPokitServicePrivate::serviceUuid, QObject::tr.
void StatusServicePrivate::characteristicRead(const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
References QString::arg, QByteArray::at, StatusService::CharacteristicUuids::buttonPress, AbstractPokitServicePrivate::characteristicRead, AbstractPokitServicePrivate::checkSize, StatusService::CharacteristicUuids::deviceCharacteristics, StatusService::CharacteristicUuids::flashLed, QString::fromUtf8, QLowEnergyCharacteristic::name, StatusService::CharacteristicUuids::name, parseDeviceCharacteristics, parseStatus, QObject::Q_EMIT, AbstractPokitServicePrivate::serviceUuid, StatusService::CharacteristicUuids::status, StatusService::CharacteristicUuids::torch, StatusService::toString, QObject::tr, QLowEnergyCharacteristic::uuid.
void StatusServicePrivate::characteristicWritten(const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
References AbstractPokitServicePrivate::characteristicWritten, StatusService::CharacteristicUuids::deviceCharacteristics, StatusService::CharacteristicUuids::flashLed, QLowEnergyCharacteristic::name, StatusService::CharacteristicUuids::name, QObject::Q_EMIT, AbstractPokitServicePrivate::serviceUuid, StatusService::CharacteristicUuids::status, StatusService::CharacteristicUuids::torch, QObject::tr, QLowEnergyCharacteristic::uuid.