MultimeterService
Mode
Make device idle.
MeterStatus
Auto-range is disabled (voltage, current and resistance modes only).
const QBluetoothUuid MultimeterService::serviceUuid
UUID of the Multimeter service.
Referenced by PokitDevice::serviceToString.
friend class TestMultimeterService
QString MultimeterService::toString(const Mode &mode)
Returns mode as a user-friendly string.
References AcCurrent, AcVoltage, Capacitance, Continuity, DcCurrent, DcVoltage, Diode, ExternalTemperature, Idle, Resistance, Temperature, QObject::tr.
Referenced by MeterCommand::outputReading, MeterCommand::serviceDetailsDiscovered, toString.
QString MultimeterService::toString(const PokitProduct product, const quint8 range, const Mode mode)
Returns range as a user-friendly string, or a null QString if mode has no ranges.
References AcCurrent, AcVoltage, Capacitance, Continuity, DcCurrent, DcVoltage, Diode, ExternalTemperature, Idle, Resistance, Temperature, CapacitanceRange::toString, CurrentRange::toString, ResistanceRange::toString, VoltageRange::toString.
QVariant MultimeterService::maxValue(const PokitProduct product, const quint8 range, const Mode mode)
Returns the maximum value for range, or the string "Auto".
If range is not a known valid enumeration value for product's mode, then a null QVariant is returned.
References AcCurrent, AcVoltage, Capacitance, Continuity, DcCurrent, DcVoltage, Diode, ExternalTemperature, Idle, CapacitanceRange::maxValue, CurrentRange::maxValue, ResistanceRange::maxValue, VoltageRange::maxValue, Resistance, Temperature.
Referenced by maxValue.
QString MultimeterService::toString(const quint8 range, const Mode mode) const
Returns range as a user-friendly string, or a null QString if mode has no ranges.
References AbstractPokitService::pokitProduct, toString.
QVariant MultimeterService::maxValue(const quint8 range, const Mode mode) const
Returns the maximum value for range, or the string "Auto".
If range is not a known valid enumeration value for the current product's mode, then a null QVariant is returned.
References maxValue, AbstractPokitService::pokitProduct.
MultimeterService::MultimeterService(QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
MultimeterService::~MultimeterService() override
Destroys this MultimeterService object.
bool MultimeterService::readCharacteristics() override
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service. Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
References readReadingCharacteristic.
bool MultimeterService::readReadingCharacteristic()
Read the Multimeter service's Reading characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered). Emits readingRead() if/when the characteristic has been read successfully.
References MultimeterService::CharacteristicUuids::reading.
Referenced by readCharacteristics.
bool MultimeterService::setSettings(const Settings &settings)
Configures the Pokit device's multimeter mode.
Returns true if the write request was successfully queued, false otherwise. Emits settingsWritten() if/when the settings have been writtem successfully.
References MultimeterServicePrivate::encodeSettings, QByteArray::isNull, QLowEnergyCharacteristic::isValid, MultimeterService::CharacteristicUuids::settings.
Referenced by MeterCommand::serviceDetailsDiscovered.
MultimeterService::Reading MultimeterService::reading() const
Returns the most recent value of the Multimeter service's Reading characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then the returned MultimeterService::Reading::value member will be a quiet NaN, which can be checked like: constMultimeterService::Readingreading=multimeterService->reading(); if(qIsNaN(reading.value)){ //Handlefailure. }
References Error, Idle, QLowEnergyCharacteristic::isValid, MultimeterServicePrivate::parseReading, MultimeterService::CharacteristicUuids::reading, QLowEnergyCharacteristic::value.
bool MultimeterService::enableReadingNotifications()
Enables client-side notifications of meter readings.
This is an alternative to manually requesting individual reads via readReadingCharacteristic(). Returns true is the request was successfully submited to the device queue, false otherwise. Successfully read values (if any) will be emitted via the readingRead() signal.
References MultimeterService::CharacteristicUuids::reading.
Referenced by MeterCommand::settingsWritten.
bool MultimeterService::disableReadingNotifications()
Disables client-side notifications of meter readings.
Instantaneous reads can still be fetched by readReadingCharacteristic(). Returns true is the request was successfully submited to the device queue, false otherwise.
References MultimeterService::CharacteristicUuids::reading.
void MultimeterService::settingsWritten()
This signal is emitted when the Settings characteristic has been written successfully.
setSettings
Referenced by MeterCommand::getService.
void MultimeterService::readingRead(const MultimeterService::Reading &reading)
This signal is emitted when the Reading characteristic has been read successfully.
readReadingCharacteristic
Referenced by MeterCommand::settingsWritten.
MultimeterService::MultimeterService(MultimeterServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.