DsoService
Command
Run free, without waiting for edge triggers.
Mode
Make device idle.
DsoStatus
Sampling has completed.
QVector<qint16> DsoService::Samples
Raw samples from the Reading characteristic.
These raw samples are (supposedly) wihtin the range -2048 to +2047, and need to be multiplied by the Metadata::scale value from the Metadata characteristc to get the true values. Also supposedly, there should be no more than 10 samples at a time, according to Pokit's current API docs. There is not artificial limitation imposed by QtPokit, so devices may begin batching more samples in future.
const QBluetoothUuid DsoService::serviceUuid
UUID of the "DSO" service.
Referenced by PokitDevice::serviceToString.
friend class TestDsoService
QString DsoService::toString(const Mode &mode)
Returns mode as a user-friendly string.
References AcCurrent, AcVoltage, DcCurrent, DcVoltage, Idle, QObject::tr.
Referenced by DsoCommand::metadataRead, DsoCommand::outputSamples, DsoCommand::serviceDetailsDiscovered, toString.
QString DsoService::toString(const PokitProduct product, const quint8 range, const Mode mode)
Returns range as a user-friendly string, or a null QString if mode has no ranges.
References AcCurrent, AcVoltage, DcCurrent, DcVoltage, Idle, CurrentRange::toString, VoltageRange::toString.
QVariant DsoService::maxValue(const PokitProduct product, const quint8 range, const Mode mode)
Returns the maximum value for range, or the string "Auto".
If range is not a known valid enumeration value for product's mode, then a null QVariant is returned.
References AcCurrent, AcVoltage, DcCurrent, DcVoltage, Idle, CurrentRange::maxValue, VoltageRange::maxValue.
Referenced by maxValue.
QString DsoService::toString(const quint8 range, const Mode mode) const
Returns range as a user-friendly string, or a null QString if mode has no ranges.
References AbstractPokitService::pokitProduct, toString.
QVariant DsoService::maxValue(const quint8 range, const Mode mode) const
Returns the maximum value for range, or the string "Auto".
If range is not a known valid enumeration value for the current product's mode, then a null QVariant is returned.
References maxValue, AbstractPokitService::pokitProduct.
DsoService::DsoService(QLowEnergyController *const pokitDevice, QObject *parent=nullptr)
Constructs a new Pokit service with parent.
DsoService::~DsoService() override
Destroys this DsoService object.
bool DsoService::readCharacteristics() override
Read all characteristics.
This convenience function will queue refresh requests of all characteristics supported by this service. Relevant *Service::*Read signals will be emitted by derived class objects as each characteristic is successfully read.
References readMetadataCharacteristic.
bool DsoService::readMetadataCharacteristic()
Reads the DSO service's Metadata characteristic.
Returns true is the read request is succesfully queued, false otherwise (ie if the underlying controller it not yet connected to the Pokit device, or the device's services have not yet been discovered). Emits metadataRead() if/when the characteristic has been read successfully.
References DsoService::CharacteristicUuids::metadata.
Referenced by readCharacteristics.
bool DsoService::setSettings(const Settings &settings)
Configures the Pokit device's DSO mode.
Returns true if the write request was successfully queued, false otherwise. Emits settingsWritten() if/when the settings have been writtem successfully.
References DsoServicePrivate::encodeSettings, QByteArray::isNull, QLowEnergyCharacteristic::isValid, DsoService::CharacteristicUuids::settings.
Referenced by fetchSamples, DsoCommand::serviceDetailsDiscovered, startDso.
bool DsoService::startDso(const Settings &settings)
Start the DSO with settings.
This is just a synonym for setSettings() except makes the caller's intention more explicit, and sanity-checks that the settings's command is not DsoService::Command::ResendData.
References DsoService::Settings::command, ResendData, setSettings, QObject::tr.
bool DsoService::fetchSamples()
Fetch DSO samples.
This is just a convenience function equivalent to calling setSettings() with the command set to DsoService::Command::Refresh. Once the Pokit device has processed this request succesffully, the device will begin notifying the Metadata and Reading characteristic, resulting in emits of metadataRead and samplesRead respectively.
References Idle, ResendData, setSettings.
DsoService::Metadata DsoService::metadata() const
Returns the most recent value of the DSO service's Metadata characteristic.
The returned value, if any, is from the underlying Bluetooth stack's cache. If no such value is currently available (ie the serviceDetailsDiscovered signal has not been emitted yet), then the returned DsoService::Metadata::scale member will be a quiet NaN, which can be checked like: constDsoService::Metadatametadata=multimeterService->metadata(); if(qIsNaN(metadata.scale)){ //Handlefailure. }
References Error, Idle, QLowEnergyCharacteristic::isValid, DsoService::CharacteristicUuids::metadata, DsoServicePrivate::parseMetadata, QLowEnergyCharacteristic::value.
bool DsoService::enableMetadataNotifications()
Enables client-side notifications of DSO metadata changes.
This is an alternative to manually requesting individual reads via readMetadataCharacteristic(). Returns true is the request was successfully submited to the device queue, false otherwise. Successfully read values (if any) will be emitted via the metadataRead() signal.
References DsoService::CharacteristicUuids::metadata.
Referenced by DsoCommand::settingsWritten.
bool DsoService::disableMetadataNotifications()
Disables client-side notifications of DSO metadata changes.
Instantaneous reads can still be fetched by readMetadataCharacteristic(). Returns true is the request was successfully submited to the device queue, false otherwise.
References DsoService::CharacteristicUuids::metadata.
bool DsoService::enableReadingNotifications()
Enables client-side notifications of DSO readings.
Returns true is the request was successfully submited to the device queue, false otherwise. Successfully read samples (if any) will be emitted via the samplesRead() signal.
References DsoService::CharacteristicUuids::reading.
Referenced by DsoCommand::settingsWritten.
bool DsoService::disableReadingNotifications()
Disables client-side notifications of DSO readings.
Returns true is the request was successfully submited to the device queue, false otherwise.
References DsoService::CharacteristicUuids::reading.
void DsoService::settingsWritten()
This signal is emitted when the Settings characteristic has been written successfully.
setSettings
Referenced by DsoCommand::getService.
void DsoService::metadataRead(const DsoService::Metadata &meta)
This signal is emitted when the Metadata characteristic has been read successfully.
readMetadataCharacteristic
Referenced by DsoCommand::settingsWritten.
void DsoService::samplesRead(const DsoService::Samples &samples)
This signal is emitted when the Reading characteristic has been notified.
beginSampling stopSampling
Referenced by DsoCommand::settingsWritten.
DsoService::DsoService(DsoServicePrivate *const d, QObject *const parent)
Constructs a new Pokit service with parent, and private implementation d.