DataLoggerServicePrivate
friend class TestDataLoggerService
DataLoggerServicePrivate::DataLoggerServicePrivate(QLowEnergyController *controller, DataLoggerService *const q)
Constructs a new DataLoggerServicePrivate object with public implementation q.
QByteArray DataLoggerServicePrivate::encodeSettings(const DataLoggerService::Settings &settings, const bool updateIntervalIs32bit)
Returns settings in the format Pokit devices expect.
If updateIntervalIs32bit is true then the Update Interval field will be encoded in 32-bit instead of 16.
References DataLoggerService::Settings::arguments, DataLoggerService::Settings::command, QDataStream::LittleEndian, DataLoggerService::Settings::mode, DataLoggerService::Settings::range, QDataStream::setByteOrder, QDataStream::setFloatingPointPrecision, QDataStream::SinglePrecision, QByteArray::size, DataLoggerService::Settings::timestamp, DataLoggerService::Settings::updateInterval, QIODeviceBase::WriteOnly.
Referenced by DataLoggerService::setSettings.
DataLoggerService::Metadata DataLoggerServicePrivate::parseMetadata(const QByteArray &value)
Parses the Metadata value into a DataLoggerService::Metatdata struct.
References QString::arg, QByteArray::at, AbstractPokitServicePrivate::checkSize, QByteArray::constData, DataLoggerService::Error, DataLoggerService::Idle, QByteArray::mid, QByteArray::size, QByteArray::toHex, AbstractPokitServicePrivate::toHexString, QObject::tr.
Referenced by characteristicChanged, characteristicRead, DataLoggerService::metadata.
DataLoggerService::Samples DataLoggerServicePrivate::parseSamples(const QByteArray &value)
Parses the Reading value into a DataLoggerService::Samples vector.
References QList::append, QString::arg, QByteArray::constData, QByteArray::mid, QByteArray::size, QList::size, AbstractPokitServicePrivate::toHexString, QObject::tr.
Referenced by characteristicChanged.
void DataLoggerServicePrivate::characteristicRead(const QLowEnergyCharacteristic &characteristic, const QByteArray &value) override
Implements AbstractPokitServicePrivate::characteristicRead to parse value, then emit a specialised signal, for each supported characteristic.
References AbstractPokitServicePrivate::characteristicRead, DataLoggerService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name, parseMetadata, QObject::Q_EMIT, DataLoggerService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DataLoggerService::CharacteristicUuids::settings, QObject::tr, QLowEnergyCharacteristic::uuid.
void DataLoggerServicePrivate::characteristicWritten(const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicWritten to parse newValue, then emit a specialised signal, for each supported characteristic.
References AbstractPokitServicePrivate::characteristicWritten, DataLoggerService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name, QObject::Q_EMIT, DataLoggerService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DataLoggerService::CharacteristicUuids::settings, QObject::tr, QLowEnergyCharacteristic::uuid.
void DataLoggerServicePrivate::characteristicChanged(const QLowEnergyCharacteristic &characteristic, const QByteArray &newValue) override
Implements AbstractPokitServicePrivate::characteristicChanged to parse newValue, then emit a specialised signal, for each supported characteristic.
References AbstractPokitServicePrivate::characteristicChanged, DataLoggerService::CharacteristicUuids::metadata, QLowEnergyCharacteristic::name, parseMetadata, parseSamples, QObject::Q_EMIT, DataLoggerService::CharacteristicUuids::reading, AbstractPokitServicePrivate::serviceUuid, DataLoggerService::CharacteristicUuids::settings, QObject::tr, QLowEnergyCharacteristic::uuid.