pokitpro.h
CapacitanceRange
Up 100nF.
CurrentRange
Up to 5µA.
ResistanceRange
Up to 30Ω.
VoltageRange
Up to 250mV.
QString PokitPro::toString(const CapacitanceRange &range)
Returns range as a user-friendly string.
References PokitPro::_100nF, PokitPro::_10uF, PokitPro::_1mF, PokitPro::AutoRange, QCoreApplication::translate.
Referenced by CapacitanceRange::toString, CurrentRange::toString, ResistanceRange::toString, VoltageRange::toString.
QVariant PokitPro::maxValue(const CapacitanceRange &range)
Returns the maximum value for range in (integer) nanofarads, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitPro::_100nF, PokitPro::_10uF, PokitPro::_1mF, PokitPro::AutoRange, QCoreApplication::translate.
Referenced by CapacitanceRange::maxValue, CurrentRange::maxValue, ResistanceRange::maxValue, VoltageRange::maxValue.
QString PokitPro::toString(const CurrentRange &range)
Returns range as a user-friendly string.
References PokitPro::_10A, PokitPro::_10mA, PokitPro::_125mA, PokitPro::_2mA, PokitPro::_300mA, PokitPro::_3A, PokitPro::_500uA, PokitPro::AutoRange, QCoreApplication::translate.
QVariant PokitPro::maxValue(const CurrentRange &range)
Returns the maximum value for range in (integer) microamps, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitPro::_10A, PokitPro::_10mA, PokitPro::_125mA, PokitPro::_2mA, PokitPro::_300mA, PokitPro::_3A, PokitPro::_500uA, PokitPro::AutoRange, QCoreApplication::translate.
QString PokitPro::toString(const ResistanceRange &range)
Returns range as a user-friendly string.
References PokitPro::_10K, PokitPro::_15K, PokitPro::_1M, PokitPro::_30, PokitPro::_3M, PokitPro::_400, PokitPro::_40K, PokitPro::_500K, PokitPro::_5K, PokitPro::_700K, PokitPro::_75, PokitPro::AutoRange, QCoreApplication::translate.
QVariant PokitPro::maxValue(const ResistanceRange &range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitPro::_10K, PokitPro::_15K, PokitPro::_1M, PokitPro::_30, PokitPro::_3M, PokitPro::_400, PokitPro::_40K, PokitPro::_500K, PokitPro::_5K, PokitPro::_700K, PokitPro::_75, PokitPro::AutoRange, QCoreApplication::translate.
QString PokitPro::toString(const VoltageRange &range)
Returns range as a user-friendly string.
References PokitPro::_10V, PokitPro::_125V, PokitPro::_250mV, PokitPro::_2V, PokitPro::_30V, PokitPro::_400V, PokitPro::_600V, PokitPro::_60V, PokitPro::AutoRange, QCoreApplication::translate.
QVariant PokitPro::maxValue(const VoltageRange &range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitPro::_10V, PokitPro::_125V, PokitPro::_250mV, PokitPro::_2V, PokitPro::_30V, PokitPro::_400V, PokitPro::_600V, PokitPro::_60V, PokitPro::AutoRange, QCoreApplication::translate.
quint8 operator+(PokitPro::CapacitanceRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.
quint8 operator+(PokitPro::CurrentRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.
quint8 operator+(PokitPro::ResistanceRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.
quint8 operator+(PokitPro::VoltageRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.