pokitmeter.h
CurrentRange
Up to 10mA.
ResistanceRange
Up to 160Ω.
VoltageRange
Up to 300mV.
QString PokitMeter::toString(const CurrentRange &range)
Returns range as a user-friendly string.
References PokitMeter::_10mA, PokitMeter::_150mA, PokitMeter::_2A, PokitMeter::_300mA, PokitMeter::_30mA, PokitMeter::AutoRange, QCoreApplication::translate.
Referenced by CurrentRange::toString, ResistanceRange::toString, VoltageRange::toString.
QVariant PokitMeter::maxValue(const CurrentRange &range)
Returns the maximum value for range in (integer) microamps, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitMeter::_10mA, PokitMeter::_150mA, PokitMeter::_2A, PokitMeter::_300mA, PokitMeter::_30mA, PokitMeter::AutoRange, QCoreApplication::translate.
Referenced by CurrentRange::maxValue, ResistanceRange::maxValue, VoltageRange::maxValue.
QString PokitMeter::toString(const ResistanceRange &range)
Returns range as a user-friendly string.
References PokitMeter::_100K, PokitMeter::_10K, PokitMeter::_160, PokitMeter::_1K5, PokitMeter::_1M, PokitMeter::_330, PokitMeter::_470K, PokitMeter::_890, PokitMeter::AutoRange, QCoreApplication::translate.
QVariant PokitMeter::maxValue(const ResistanceRange &range)
Returns the maximum value for range in (integer) ohms, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitMeter::_100K, PokitMeter::_10K, PokitMeter::_160, PokitMeter::_1K5, PokitMeter::_1M, PokitMeter::_330, PokitMeter::_470K, PokitMeter::_890, PokitMeter::AutoRange, QCoreApplication::translate.
QString PokitMeter::toString(const VoltageRange &range)
Returns range as a user-friendly string.
References PokitMeter::_12V, PokitMeter::_2V, PokitMeter::_300mV, PokitMeter::_30V, PokitMeter::_60V, PokitMeter::_6V, PokitMeter::AutoRange, QCoreApplication::translate.
QVariant PokitMeter::maxValue(const VoltageRange &range)
Returns the maximum value for range in (integer) millivolts, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned.
References PokitMeter::_12V, PokitMeter::_2V, PokitMeter::_300mV, PokitMeter::_30V, PokitMeter::_60V, PokitMeter::_6V, PokitMeter::AutoRange, QCoreApplication::translate.
quint8 operator+(PokitMeter::CurrentRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.
quint8 operator+(PokitMeter::ResistanceRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.
quint8 operator+(PokitMeter::VoltageRange range) noexcept
Returns range as a quint8 as a convenience for assigning to services' settings.range members.