pokitproducts.cpp
static Q_LOGGING_CATEGORY(lc, "dokit.pokit.products", QtInfoMsg)
Logging category for this file.
QTPOKIT_BEGIN_NAMESPACE QString toString(const PokitProduct product)
Returns product as user-friendly string.
References QString::arg, PokitMeter, PokitPro, QCoreApplication::translate.
Referenced by AbstractPokitServicePrivate::createServiceObject, DeviceCommand::deviceDiscovered.
bool isPokitProduct(const QBluetoothDeviceInfo &info)
Returns true if info describes a Pokit device.
Currently, this is based on whether or not info's service UUIDs includes a known Pokit Status service, but this test criteria might be swapped for something else sometime.
References isPokitProduct, QBluetoothDeviceInfo::serviceUuids.
Referenced by DeviceCommand::deviceDiscovered, PokitDiscoveryAgentPrivate::deviceDiscovered, PokitDiscoveryAgentPrivate::deviceUpdated, isPokitProduct, isPokitProduct.
PokitProduct pokitProduct(const QBluetoothDeviceInfo &info)
Returns the PokitProduct corresponding the Bluetotoh device info.
If info is not a Pokit device, then result is undefined. isPokitProduct
References pokitProduct, QBluetoothDeviceInfo::serviceUuids.
Referenced by DeviceCommand::deviceDiscovered, pokitProduct, pokitProduct.
bool isPokitProduct(const QList< QBluetoothUuid > &serviceUuids)
Returns true if serviceUuids contains a known Pokit Status service UUID.
Currently, this is the only known way to detect a Pokit device.
References QList::contains, StatusService::ServiceUuids::pokitMeter, StatusService::ServiceUuids::pokitPro.
bool isPokitProduct(const QLowEnergyController &controller)
Returns true if controller describes a Pokit device.
Currently, this is based on whether or not controller's service UUIDs includes a known Pokit Status service, but this test criteria might be swapped for something else sometime. isPokitProduct
References isPokitProduct, QLowEnergyController::services.
PokitProduct pokitProduct(const QList< QBluetoothUuid > &serviceUuids)
Returns the PokitProduct corresponding to the Bluetooth serviceUuids.
Currently, this is based on whether or not servceUuids includes a known Pokit Status service, but this test criteria might be swapped for something else sometime. isPokitProduct
References QList::contains, PokitMeter, StatusService::ServiceUuids::pokitMeter, PokitPro, StatusService::ServiceUuids::pokitPro, QCoreApplication::translate.
PokitProduct pokitProduct(const QLowEnergyController &controller)
Returns the PokitProduct corresponding to the Bluetooth controller.
Currently, this is based on whether or not controller's service UUIDs includes a known Pokit Status service, but this test criteria might be swapped for something else sometime. isPokitProduct
References pokitProduct, QLowEnergyController::services.
QTPOKIT_EXPORT QString CapacitanceRange::toString(const PokitProduct product, const quint8 range)
Returns product's capacitance range as a human-friendly string.
Since Pokit Meters do not support capacitance measurement, product should not be PokitProduct::PokitMeter. PokitPro::toString(const PokitPro::CapacitanceRange &range)
References QString::arg, PokitMeter, PokitPro, PokitPro::toString, QCoreApplication::translate.
Referenced by MultimeterService::toString.
QTPOKIT_EXPORT QVariant CapacitanceRange::maxValue(const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) nanofarads, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned. Since Pokit Meters do not support capacitance measurement, product should not be PokitProduct::PokitMeter. PokitPro::maxValue(const PokitPro::CapacitanceRange &range)
References QString::arg, PokitPro::maxValue, PokitMeter, PokitPro, QCoreApplication::translate.
Referenced by MultimeterService::maxValue.
QTPOKIT_EXPORT QString CurrentRange::toString(const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
PokitMeter::toString(const PokitMeter::CurrentRange &range) PokitPro::toString(const PokitPro::CurrentRange &range)
References QString::arg, PokitMeter, PokitPro, PokitMeter::toString, PokitPro::toString, QCoreApplication::translate.
Referenced by DataLoggerService::toString, DsoService::toString, MultimeterService::toString.
QTPOKIT_EXPORT QVariant CurrentRange::maxValue(const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) microamps, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned. PokitMeter::maxValue(const PokitMeter::CurrentRange &range) PokitPro::maxValue(const PokitPro::CurrentRange &range)
References QString::arg, PokitMeter::maxValue, PokitPro::maxValue, PokitMeter, PokitPro, QCoreApplication::translate.
Referenced by DataLoggerService::maxValue, DsoService::maxValue, MultimeterService::maxValue.
QTPOKIT_EXPORT QString ResistanceRange::toString(const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
PokitMeter::toString(const PokitMeter::ResistanceRange &range) PokitPro::toString(const PokitPro::ResistanceRange &range)
References QString::arg, PokitMeter, PokitPro, PokitMeter::toString, PokitPro::toString, QCoreApplication::translate.
Referenced by MultimeterService::toString.
QTPOKIT_EXPORT QVariant ResistanceRange::maxValue(const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) ohms, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned. PokitMeter::maxValue(const PokitMeter::ResistanceRange &range) PokitPro::maxValue(const PokitPro::ResistanceRange &range)
References QString::arg, PokitMeter::maxValue, PokitPro::maxValue, PokitMeter, PokitPro, QCoreApplication::translate.
Referenced by MultimeterService::maxValue.
QTPOKIT_EXPORT QString VoltageRange::toString(const PokitProduct product, const quint8 range)
Returns product's current range as a human-friendly string.
PokitMeter::toString(const PokitMeter::VoltageRange &range) PokitPro::toString(const PokitPro::VoltageRange &range)
References QString::arg, PokitMeter, PokitPro, PokitMeter::toString, PokitPro::toString, QCoreApplication::translate.
Referenced by DataLoggerService::toString, DsoService::toString, MultimeterService::toString.
QTPOKIT_EXPORT QVariant VoltageRange::maxValue(const PokitProduct product, const quint8 range)
Returns the maximum value for product's range in (integer) millivolts, or the string "Auto".
If range is not a known valid value, then an null QVariant is returned. PokitMeter::maxValue(const PokitMeter::VoltageRange &range) PokitPro::maxValue(const PokitPro::VoltageRange &range)
References QString::arg, PokitMeter::maxValue, PokitPro::maxValue, PokitMeter, PokitPro, QCoreApplication::translate.
Referenced by DataLoggerService::maxValue, DsoService::maxValue, MultimeterService::maxValue.